options:
  feature-flags:
    type: string
    default: ''
    description: |
      Comma-delimited list of feature flags to be used. Each feature flag specified is set to 'True'. Example: 'DEBUG,FEATURE_FLAG_AUTH'. (non-conclusive) List of supported flags:
        - DEBUG: run h_api in debug mode
        - FEATURE_FLAG_AUTH: Turn on authentication on h_api
  juju-admin-password:
    type: string
    default: 'admin'
    description: |
      MUST NOT BE LEFT BLANK
  port:
    type: string
    default: '5000'
    description: |
      The port on which the API will be listening.
  charm-dir:
    type: string
    default: '/home/ubuntu/local_charms'
    description: |
      The location where the api will search for local charms, when the app_name is prefixed with "local:<app_name>"
