options:
  charm-dir:
    type: string
    default: '/home/ubuntu/qrama-charms'
    description: |
      The location where the api will search for local charms, when the app_name is prefixed with "local:<app_name>"
  host:
    type: string
    default: "127.0.0.1"
    description: listen address. When left at the default value, defaults to internal ip address.
