options:
  api-dir:
    type: string
    default: '/opt/sojobo_api'
    description: |
      The location where the api will be installed
  api-user:
    type: string
    default: 'sojobo'
    description: |
      The linux user that will be created to run the api
  nginx-group:
    type: string
    default: 'www-data'
    description: |
      The linux group of which nginx is a member
  juju-admin-password:
    type: string
    default: 'admin'
    description: |
      MUST BE CHANGED
  charm-dir:
    type: string
    default: '/home/ubuntu/local_charms'
    description: |
      The location where the api will search for local charms, when the app_name is prefixed with "local:<app_name>"
  https:
    type: boolean
    default: false
    description: |
      If the Sojobo should run over https or http. Https is highly recommended!!
  host:
    type: string
    default: "127.0.0.1"
    description: listen address
