"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": |
      the status of service-affecting packages will be set to this
      value in the dpkg database. valid values are "install" and "hold".
  "install_sources":
    "description": |
      list of extra apt sources, per charm-helpers standard
      format (a yaml list of strings encoded as a string). each source
      may be either a line that can be added directly to
      sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
      personal package archives, or a distribution component to enable.
    "type": "string"
    "default": |
      -  "deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main"
  "install_keys":
    "description": |
      list of signing keys for install_sources package sources, per
      charmhelpers standard format (a yaml list of strings encoded as
      a string). the keys should be the full ascii armoured gpg public
      keys. while gpg key ids are also supported and looked up on a
      keyserver, operators should be aware that this mechanism is
      insecure. null can be used if a standard package signing key is
      used that will already be installed on the machine, and for ppa
      sources where the package signing key is securely retrieved from
      launchpad.
    "type": "string"
    "default": |
      - 561F9B9CAC40B2F7
  "user":
    "type": "string"
    "default": "ubuntu"
    "description": "user to install the tools for"
  "controllers_yaml":
    "type": "string"
    "default": ""
    "description": |
      base64 encoded contents of ~/.local/share/juju/controllers.yaml
  "credentials_yaml":
    "type": "string"
    "default": ""
    "description": |
      base64 encoded contents of ~/.local/share/juju/credentials.yaml
  "clouds_yaml":
    "type": "string"
    "default": ""
    "description": |
      base64 encoded contents of ~/.local/share/juju/clouds.yaml
  "port":
    "type": "int"
    "default": !!int "80"
    "description": |
      NGINX listen port
  "host":
    "type": "string"
    "default": "127.0.0.1"
    "description": "listen address"
  "api-dir":
    "type": "string"
    "default": "/opt/sojobo_api"
    "description": |
      The location where the api will be installed
  "api-user":
    "type": "string"
    "default": "sojobo"
    "description": |
      The linux user that will be created to run the api
  "nginx-group":
    "type": "string"
    "default": "www-data"
    "description": |
      The linux group of which nginx is a member
  "juju-admin-password":
    "type": "string"
    "default": "admin"
    "description": |
      MUST BE CHANGED
  "charm-dir":
    "type": "string"
    "default": "/home/ubuntu/local_charms"
    "description": |
      The location where the api will search for local charms, when the app_name is prefixed with "local:<app_name>"
  "setup":
    "type": "string"
    "default": "httpsletsencrypt"
    "description": |
      Choose the type of install: http [http], https [httpsclient] with client certificates, https [httpsletsencrypt] with
      letsencrypt setup. If an option is entered which does not match [http, httpsclient, httpsletsencrypt], defaults to http.
      the setup and config for letsencrypt is a manual process, which is documented in the readme.
  "fullchain":
    "type": "string"
    "default": ""
    "description": |
      Specify the location of the ssl fullchain. Leave blank if you want the charm to setup a letsencrypt certificate
  "privatekey":
    "type": "string"
    "default": ""
    "description": |
      Specify the location of the ssl privatekey. Leave blank if you want the charm to setup a letsencrypt certificate
  "dhparam":
    "type": "string"
    "default": "/etc/nginx/ssl/dhparam.pem"
    "description": |
      Location of the DH.pem file
